# This file is based on contents of:
# https://github.com/snapcraft-docs/offlineimap/blob/master/snapcraft.yaml
#
# Contents of this YAML template and snapcraft.yaml in GitHub repo should
# be kept in sync to make sure tutotials work as expected.

name: ${name}
version: git
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.
confinement: devmode
base: core18

parts:
  ${name}:
    plugin: python
    python-version: python2
    source: .
    stage-packages:
      - python-six

apps:
  ${name}:
    command: bin/${name}
